GoogleSearch/GoogleSearch/urls.py
#import include if not imported
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('search.urls')),
    
]

GoogleSearch/google/urls.py
from . import views
from django.urls import path

app_name = "google"

urlpatterns = [
    path("", views.main_page, name="main_page"),
    path("terms/", views.terms_page, name="terms_page"),
]

GoogleSearch/home_page/urls.py
from . import views 
from django.urls import path

app_name ='home_page'

urlpatterns=[
    path('',views.home_page,name='home_page'),
]

GoogleSearch/main/urls.py
from . import views
from django.urls import path 

app_name="main"

urlpatterns = [
    path("home/" , views.home , name="home_page"),
    path("terms/" , views.term , name="terms_page"),
    path("style/", views.style , name="style_page"),
]

GoogleSearch/search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('', views.home, name='home'),
    path('terms', views.terms_of_service, name='terms_of_service'),
]

GoogleSearch/google/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

# Create your views here.
def main_page(request:HttpRequest):

    return render(request,'google/main_page.html')

def terms_page(request:HttpRequest):

    return render(request,'google/terms_page.html')

GoogleSearch/home_page/views.py
from django.shortcuts import render
from django.http import HttpRequest , HttpResponse

# Create your views here.

def home_page(request:HttpRequest):
    return render (request, 'home_page/browser.html')

GoogleSearch/main/views.py
from django.shortcuts import render
from django.http import HttpRequest,HttpResponse

# Create your views here.

def home(request: HttpRequest):
 return render(request,"main/home.html")

def term(request: HttpRequest):
 return render(request,"main/terms.html")

def style(request: HttpRequest):
 return render(request,"main/style.html")

GoogleSearch/search/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(request, 'search/home.html')

def terms_of_service(request):
    return render(request, 'search/terms.html')

GoogleSearch/google/templates/google/main_page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Google</title>
    <link rel="stylesheet" href="{% static 'styles/main_page.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Josefin+Sans:ital,wght@0,100..700;1,100..700&family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap" rel="stylesheet">
</head>


<body>

    <header>
        <nav class="top-nav">
            <div class="a-nav">
                <a href ="">Gmail</a>
                <a href ="">Images</a>  
            </div>
            <div>
                <span class="material-symbols-outlined">apps</span>
            </div>
            <div>
                <button class="button-signin" type="button">Sign in</button>
            </div>
        </nav>
    </header>

    
    <div class="main">
        <img src="{% static 'images/google-logo.png' %}" alt="google logo" class="google-logo" />
        <div class="search-box">
            <input type="text" class="search-input" placeholder="Search..">
            <div class="search-icon">
                <span class="material-symbols-outlined">search</span>
                <div class="icons">
                    <img src="{% static 'images/mircophone.png' %}" alt="mircophone" class="icon"/>   
                    <img src="{% static 'images/camera.png' %}" alt="camera" class="icon"/>
                </div>
            </div>

            <div class="search-buttons">
                <button class="button" type="button">Google Search</button>
            <button class="button" type="button">I'm Feeling Lucky</button>
            </div>
        </div>
        <div><h6 class="inter-font">Google offered in: <span style="color: blue;">العربية</span></h6></div>
    </div>

    


    <footer>
        <h4>saudi Arabia</h4>
        <nav class="bottom-nav">
            <div class="bottom-1" >
                <a href="">About</a>
                <a href="">Advertising</a>
                <a href="">Business</a>
                <a href="">How Search works</a>
            </div>
            <div class="bottom-2">
                <a href="">Privacy</a>
                <a href="/terms/">Terms</a>
                <a href="">Settings</a>
            </div>
        </nav>
    </footer>
  
</body>
</html>

GoogleSearch/google/templates/google/terms_page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms</title>
    <link rel="stylesheet" href="{% static 'styles/main_page.css' %}">
    <link rel="stylesheet" href="{% static 'styles/main_page.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Josefin+Sans:ital,wght@0,100..700;1,100..700&family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="top-nav">
            <div class="a-nav">
                <a href ="">Gmail</a>
                <a href ="">Images</a>  
            </div>
            <div>
                <span class="material-symbols-outlined">apps</span>
            </div>
            <div>
                <button class="button-signin" type="button">Sign in</button>
            </div>
        </nav>
    </header>
    <h1>Proccessing..</h1>

</body>
</html>

GoogleSearch/main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="icon"
      type="image/x-icon"
      href="{% static 'icon/Google.png' %}"
    />
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    {% block style %} {% endblock %}
    <title>{% block title %} Google{% endblock %}</title>
  </head>
  <body>
    <nav>
      <a href="#">Gmail</a>
      <a href="#">Images</a>
      <img src="{% static "icon/apps.png" %}" />
      <button>Sign in</button>
    </nav>
    {% block content %}
    
    {% endblock content %}
    <footer>
      <h4>Saudi Arabia</h4>
      <div class="links">
        <div class="link-1">
          <a href="#">About</a>
          <a href="#">Advertising</a>
          <a href="#">Business</a>
          <a href="#">How Search works</a>
        </div>
        <div class="link-2">
          <a href="#">Privacy</a>
          <a href="{% url "main:terms_page" %}">Terms</a>
          <a href="#">Settings</a>
        </div>
      </div>
    </footer>
  </body>
</html>

GoogleSearch/main/templates/index.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
    {% block style %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {% endblock style %}
    {% block title %} Google{% endblock title %}
  </head>
  <body>
    
    {% block content %} 
    <section class="section-1">
      <img src="{% static "images/google-logo.png" %}" class="logo" />
      <form>
        <br /><br />
        <div class="s-box">
          <img src="{% static "icon/search.svg"%}" class="search-icon" />
          <input type="text" class="s-input" />
          <img src="{% static "icon/camera.png"%}" class="camera-icon" />
          <img src="{% static "icon/mircophone.png"%}" class="vs-icon" />
          <input type="submit" class="s-btn" value="Google Search" />
          <input type="submit" class="s-btn" value="I'm Feeling Lucky" />
        </div>
      </form>
      <div class="lang">
        Google offered in:
        <a href="#">العربية</a>
      </div>
    </section>
    {% endblock %}
    
  </body>
</html>

GoogleSearch/main/templates/main/Terms.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Google Terms</title>
    <link rel="icon" href="https://cdn.iconscout.com/icon/free/png-256/free-google-152-189813.png">

    <link href="https://fonts.cdnfonts.com/css/google-sans" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Oswald:wght@200..700&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

    <style>
        @import url('https://fonts.cdnfonts.com/css/google-sans');

          *{
            padding: 0px;
            margin: 0px;
        }
        nav{
            position:sticky;
            top: 0px;
            left: 0px;
            display: flex;
            flex-direction: row;
            justify-content:right;
            padding: 10px 20px;
            column-gap: 15px;
            font-size: 14px;
            line-height: 17px;
            vertical-align: middle;
            
        }
        nav a{
            text-decoration: none;
            width: 50px;
            height: auto;
            color:rgba(0, 0, 0, .87);
            line-height: 24px;
            padding-right: 10px; ;

        }
        nav a:hover{
            text-decoration:underline;
        }
        #sign_in{
            background-color:  rgb(26,115,232);
            color: white;
            width: 96px;
            height: 35.88px;
            border-radius: 4px;
            border: none;
            
        }
        #google_app{
            height: 40px;
            border: none;
            background: none;
            
        }
        #google_app:hover{
            border-radius: 25px;
            background-color: rgba(0, 0, 0, 0.337);
        }
        #sign_in:hover{
            background-color:rgb(7, 103, 228) ;
        }
        .nav_all{
         word-spacing: 10px;
         padding-top: 8px;
        }
        .google_terms{
            width: 1100px;
            margin-top: 5%;
            margin-left: 21%;
            
        }
        a{
            text-decoration: none;
        }
        .content{
            /* font-size:larger; */
            margin-left: 25%;
            padding: 30px;
            border: black 2px none;
            width: 900px;
            line-height: 40px;
            font-family:  Arial, sans-serif;
            font-weight: 2px;
        }
        .content h1,h3{
            font-family: 'Product Sans Medium', sans-serif;
            
           
        font-style: normal;     
        }
    
    </style>
</head>
<body>
    <nav >
        <div class="nav_all">
            <a href="#">Gmail</a>
            <a href="#">image</a>
        </div>
        <div>
            <button id="google_app"><img  src="{% static 'images/google_app.png'%}" alt=""></button>
        </div>
        <button id="sign_in">Sign in</button>
    </nav>
    <div>    
        <img class="google_terms" src="https://www.gstatic.com/identity/boq/policies/privacy/tos_main_illustration.svg" alt="">
        <div class="content">
        <h1>Google Terms of Service</h1>
        <p>Effective as of January 5, 2022| <a href="#">Archived versions</a> |<a href="#"> Download PDF</a> </p>
            
       <p> <a href="#">Country version: </a> Saudi Arabia </p> 
        <h3>What's covered in these terms</h3> 
            
        <h4>We understand that it can be tempting to skip these Terms of Service, but it's important to establish what you can expect from us when using Google <a href="#">services</a> and what we expect from you.</h4> 
            
        <p> These Terms of Service reflect <a href="#">how Google operates and the laws that apply to our company</a>, as well as some things we always believe are true. Accordingly, these terms help define the relationship between Google and you as you interact with our services.</p>
    </div>
    </div>
    </body>
</html>

GoogleSearch/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link href="{% static 'style_css/base.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

</head>
<body>

   <header> 
 
 <div class= "right-nav">
 <a href="/home/">Basic</a>
 <a href="https://mail.google.com/mail/">Gmail</a>
  <a href="https://www.google.com/imghp?hl=en&tab=ri&ogbl">Images</a>
  <span id = "apps"class="material-symbols-outlined">apps</span>
  <a href="https://accounts.google.com/ServiceLogin?hl=ar&passive=true&continue=https://www.google.com/search%3Fq%3Dgoogle%26oq%3Dgoogle%26gs_lcrp%3DEgZjaHJvbWUyBggAEEUYOTIGCAEQRRg7MgYIAhBFGDsyBggDEEUYOzIGCAQQRRg8MgYIBRBFGDwyBggGEEUYPTIGCAcQRRg80gEINjcwM2owajGoAgCwAgA%26sourceid%3Dchrome%26ie%3DUTF-8&ec=GAZAAQ"><button class="signbutton" type="button">Sign in</button></a>
 </div>

</header>


<div class = "SA">
<a href="/">Saudi Arabia</a>
</div>

<footer>

    <div class= "left-footer">
    
        <a href="https://about.google/?utm_source=google-SA&utm_medium=referral&utm_campaign=hp-footer&fg=1">About</a>
        <a href="https://www.google.com/intl/ar_sa/ads/?subid=ww-ww-et-g-awa-a-g_hpafoot1_1!o2&utm_source=google.com&utm_medium=referral&utm_campaign=google_hpafooter&fg=1">Advertising</a>
        <a href="https://www.google.com/services/?subid=ww-ww-et-g-awa-a-g_hpbfoot1_1!o2&utm_source=google.com&utm_medium=referral&utm_campaign=google_hpbfooter&fg=1">Business</a>
        <a href="https://google.com/search/howsearchworks/?fg=1">How Search Works</a>
    </div>

     <div class ="right-footer">
        <a href="https://policies.google.com/privacy?hl=ar-SA&fg=1">Privacy</a>
        <a href="/terms/">Terms</a>
        <a href="/">Settings</a>
    </div>

</footer>
    {% block content %}

    {% endblock %}
    
</body>
</html>

GoogleSearch/main/templates/main/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cabin:ital,wght@0,400..700;1,400..700&display=swap" rel="stylesheet">
    <link href="{% static 'style_css/home_page.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

</head>
<body>
<header> 
 
 <div class= "right-nav">
 <a href="https://mail.google.com/mail/">Gmail</a>
  <a href="https://www.google.com/imghp?hl=en&tab=ri&ogbl">Images</a>
  <span id = "apps"class="material-symbols-outlined">apps</span>
  <a href="https://accounts.google.com/ServiceLogin?hl=ar&passive=true&continue=https://www.google.com/search%3Fq%3Dgoogle%26oq%3Dgoogle%26gs_lcrp%3DEgZjaHJvbWUyBggAEEUYOTIGCAEQRRg7MgYIAhBFGDsyBggDEEUYOzIGCAQQRRg8MgYIBRBFGDwyBggGEEUYPTIGCAcQRRg80gEINjcwM2owajGoAgCwAgA%26sourceid%3Dchrome%26ie%3DUTF-8&ec=GAZAAQ"><button class="signbutton" type="button">Sign in</button></a>
 </div>

</header>


<div class="logo"> 
 <img src="{% static 'images/google-logo.png' %}" />
</div>

<div class="search">
  <i class="material-icons">search</i>
  <input class ="search-bar"type="text" placeholder="Search..">
  <span> <img class ="mic"src="{% static 'images/mircophone.png' %}" />
  <img class ="cam"src="{% static 'images/camera.png' %}" /></span>
</div>



</div>
    <div class="buttons">
      <button class="button" type="button">Google Search</button>
      <button class="button" type="button">I'm Feeling Lucky</button>
     </div>
    
    <div class="offered">
    <p>Google offered in :</p>
    <a href="/">العربية</a>
    </div>

<div class = "SA">
<a href="/">Saudi Arabia</a>
</div>

<footer>

    <div class= "left-footer">
    
        <a href="https://about.google/?utm_source=google-SA&utm_medium=referral&utm_campaign=hp-footer&fg=1">About</a>
        <a href="https://www.google.com/intl/ar_sa/ads/?subid=ww-ww-et-g-awa-a-g_hpafoot1_1!o2&utm_source=google.com&utm_medium=referral&utm_campaign=google_hpafooter&fg=1">Advertising</a>
        <a href="https://www.google.com/services/?subid=ww-ww-et-g-awa-a-g_hpbfoot1_1!o2&utm_source=google.com&utm_medium=referral&utm_campaign=google_hpbfooter&fg=1">Business</a>
        <a href="https://google.com/search/howsearchworks/?fg=1">How Search Works</a>
    </div>

     <div class ="right-footer">
        <a href="https://policies.google.com/privacy?hl=ar-SA&fg=1">Privacy</a>
        <a href="/terms/">Terms</a>
        <a href="/">Settings</a>
    </div>

</footer>


</body>
</html>

GoogleSearch/main/templates/main/home_index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Google</title>
    <link href="{% static 'style/home_style.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
</head>
<body>
    <nav>
        <div class="nav_bar">
            <a href="">Gmail</a>
            <a href="">Images</a>
        </div>
        <span id="apps-icon" class="material-symbols-outlined">
            apps
            </span>
            <button class="signing">Sign in</button>
    </nav>

    <section class="searching-bar">
        <img class="logo"src="{% static 'image/google-logo.png'%}" />
        <form>
            <span id="search-icon"class="material-symbols-outlined">
                search
            </span>
            <img class="mic" src="{% static 'image/mircophone.png'%}">
            <img class="cam" src="{% static 'image/camera.png'%}">
            <input class="search-input" type="text">
            <div class="buttons">
                <button>Google Search</button>
                <button>I'm Feeling Lucky</button>
            </div>
            <p class="translation">Google offered in:  <a class="arabic" href=""> العربية </a></p>
        </form>
    </section>

    <footer>
        <div class="panel">
            <p class="country">Saudi Arabia</p>
        </div>
        <div class="panel">
            <div class="left-side">
                <a href="">About</a>
                <a href="">Advertising</a>
                <a href="">Business</a>
                <a href="">How Search Work</a>
            </div>
            <div class="right-side">
                <a href="">Privacy</a>
                <a href="{% url 'main:terms_page'  %}">Terms</a>
                <a href="">Settings</a>
            </div>
        </div>
    </footer>
</body>
</html>

GoogleSearch/main/templates/main/home_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link href="{% static 'style/home.css' %}" rel="stylesheet" />
    
</head>

<body>
    <header>
        <nav class="main_nav">
            <ul class="nav">
            <li><a href="https://mail.google.com/mail/u/0/?tab=rm&ogbl#inbox">Gmail</a></li>
            <li><a href="https://www.google.com/imghp?hl=ar&tab=ri&authuser=0&ogbl">imege</a></li>
            <li><span class="app">apps</span></li>
            <li><button>Sign in</button></li>
            </ul>
        </nav>
    </header>
    <div class="logo">
             <img src="{% static 'image/google-logo.png' %}" alt="google logo" />   
    <div class="search">
        <div class="search_input">
            <input type="text">
            <span class="material-symbols-outlined">
                search
            </span>
        </div>
    </div>
        <div class="icon">
                <img src="{% static 'image/mircophone.png' %}" alt="mircopphone">
                <img src="{% static 'image/camera.png' %}" alt="camera">
        </div>
    </div>
        <div class="button">
            <button>Google Search </button>
            <button>I'm Feeling Luck</button>  
        </div>
        <div>
            <ul class="langugees">
                <li>Google offered in:</li>
                <li><a href="#">العربية</a></li>
            </ul>
            
        </div>
    <footer>
        <div class="footer">
            <div class="country">
                <p>Saudi Arabia</p>
            </div>
                <div class="about">
                    <ul>
                        <li><P>About</P></li>
                        <li><P>Advertising</P></li>
                        <li><P>Business</P></li>
                        <li><P>How Search works</P></li>
                    </ul>
                </div>
                <div class="terms">
                        <ul>
                            <li><P>Privacy</P></li>
                            <li><a href="terms_page.html">Temes</a></li>
                            <li><P>Setting</P></li>
                        </ul>
                </div>
        </div>
    </footer>
    
</body>
</html>

GoogleSearch/main/templates/main/main_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Google</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
</head>
<style>

* {
     padding:0px;
    margin: 0px;
   box-sizing: border-box;
   font-family: 'arial',sans-serif;
}
section{
    position: relative;
    width: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
}
section header{
    position: absolute;
    top: 0;
    width: 100%;
    display: flex;
    justify-content: flex-end;
    padding: 20px;
}

section header ul{
    display: flex;
    justify-content: center;
    align-items: center;
}
section header ul li {
    list-style: none;
    margin-left: 20px;
}
section header ul li a{
    color: black;
    text-decoration: none;
    font-size: 13px;
}
section header ul li button{
    background: #4584ef;
    border: blue;
    outline: none;
    padding: 8px 14px;
    color: white;
    font-size: 14px;
    font-weight: 700;
    border-radius: 3px;
}
section.main {
    width: 580px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
}
section .main .searchBox{
   position: relative;
   width: 100%;
   margin-top: 20px;

}
section .main .searchBox .search{
width: 100%;
padding: 13px;
padding-left: 45px;
padding-right: 60px;
border-radius: 30px;
border: 1px solid #ccc;
outline: none;
font-size: px;
}
section .main .searchBox .icons{
    position: absolute;
    top: 0;
    width: 100%;
    display: flex;
    padding: 12px 20px;
    justify-content: flex-end;
    align-items: center;
    pointer-events: none;
}
section .main .buttons{
    margin-top: 20px;  
}
section .main .buttons button{
    margin: auto;
    padding: 12px 20px;
    color: #555;
    font-size: 14px;
    border: none;
    cursor: pointer;
    border-radius: 4px;
    border: 1px solid transparent;
    outline: none;
}
section .main .buttons button:hover{
border: 1px solid #ccc;
}
section .main .languages{
    display: flex;
    margin-top: 30px;
}
section .main .languages li{
    list-style: none;
    margin: 0 5px;
    font-size: 13px;
}
section .main .languages li a :hover
{
    text-decoration: none;
    color: black;
}
section .footer{
    position: absolute;
    bottom: 0;
    left: 0; 
    width: 100px; 
    background: white;
}
section .footer .row{
    padding: 15px 25px;
    border-top: 1px solid crimson;  
}
section .footer .row .row2{
    display: flex;
    justify-content: space-between;
}
section .footer .row .row2 ul{
    display: flex;
}
section .footer .row .row2 ul li{
    list-style: none;
}
section .footer .row .row2 ul li a{
    text-decoration: none;
    font-size: 14px;
    color: rgb(61, 64, 66);
    margin-right: 25px;
}
section .footer .row .row2 ul:nth-child(2) li a{
    text-decoration: none;
    font-size: 14px;
    color: rgb(61, 64, 66);
    margin-right: 0px;
    margin-left: 25px;
}

</style>
<body>

<section>
    <header>
        <ul>
            <li><a href="#">Gmail</a></li>
            <li><a href="#">Images</a></li>
            <li><span class="material-symbols-outlined">
                apps
                </span></li>
            <li><button>Sing In</button></li>
        </ul>
    </header>
    <div class="main">
        <img src="{% static 'images/google-logo.png' %}" >
    <div class="searchBox">
        <input type="text" class="search">
        <div class="icons">
            <div><img src="{% static 'images/mircophone.png' %}"width=20></div>
            <div><img src="{% static 'images/camera.png' %}"width=20 ></div>
            <li><span class="material-symbols-outlined">
                search
                </span> 
        </div>
    </div>
    <div class="buttons">
        <button>Google Search</button>
        <button>I,m Feeling Lucky</button>
    </div>
    <ul class="languages">
    <li>Google offered in :</li>
    <li><a href="#">العربية</a></li>
    </ul>
    </div>
    <div class="footer">
        <div class="row1 row1">
            <p class="country">Saudi Arabia</p>
        </div>
        <div class="row2 row2"> 
            <ul>
                <li><a href="#">Advertising</a></li> 
                <li><a href="#">Business</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">How search works</a></li>
            </ul>
            <ul>
                <li><a href="#">Privacy</a></li>
                <li><a href="#">Terms</a></li>
                <li><a href="#">Settings</a></li>
            </ul>
        </div>
    </div>

</section>       

GoogleSearch/main/templates/main/style.html
{% extends 'main/base.html' %}
{% block title %} Style Google Search {% endblock %}

{% block content %}


<div class="logo"> 
 <img src="/static/images/google-logo-glow.png" />
</div>

<dive class = "box">  </div>
<div class="search">
  <i class="material-icons">search</i>
  <input class ="search-bar"type="text" placeholder="Search..">

</div>

</div>
    <div class="buttons">
      <button class="button" type="button">Google Search</button>
      <button class="button" type="button">I'm Feeling Lucky</button>
     </div>
    




{% endblock %}

GoogleSearch/main/templates/main/term_base.html
{% extends 'main/termsOfService.html'%}

GoogleSearch/main/templates/main/terms_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>